spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_micro_blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: "070310"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

myblog:
  security:
    jwt-key: feue666666
    token-expired-in: 3600